name = "reverse-proxy"
account_id = ""
zone_id = ""
route = "*finsweet.com/*"
type = "javascript"
compatibility_date = "2022-04-01"

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "./index.mjs"
dir = "build"